### PR TITLE
Feat/convert to posm extract format

### PR DESCRIPTION
**Pull request by jofomah**

### CODE REVIEW

**Comment by readevalprint** [comment]
Hey this looks great, two questions, does the settings have to be yaml? and check out flake8.readthedocs.org and https://pypi.python.org/pypi/autopep8/

**Comment by jofomah** [comment]
@readevalprint 
- am using yaml because they used that in POSM but the settings does not have to be in yaml.
- thanks, i will add the PEP8 formatter along with tests and docs hopefully today or tomorrow as soon as finish off the remaining parts.

**Comment by jofomah** [comment]
- ~~read admin levels dynamically from settings while setting hierarchies~~
- add unit tests

**Comment by readevalprint** [comment]
+1

**Pull request merged**
